# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      #POSTGRES_DB: "test_db" # name db
      #POSTGRES_USER: "test-admin-user" # name user
      POSTGRES_PASSWORD: "pass" # pass user
      #PGDATA: "/var/lib/postgresql/data/pgdata" # db location
    volumes:
      - ./DB:/var/lib/postgresql/data/ # db location first
      #- ./DB_new:/var/lib/postgresql/data/ # db location second
      - ./Backup:/var/lib/postgresql/Backup # Backup location
    ports:
      - 5432:5432

# Из примера докерхаба постгреса, пусть тоже весит
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080