---
- name: Get kuber config
  hosts: master_01
  become_user: root
  remote_user: ubuntu
  tasks:
    - name: Create a directory if it does not exist
      become: yes
      ansible.builtin.file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'
    - name: Copy config
      become: yes
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        mode: '0644'
        remote_src: yes
    - name: kubectl get nodes
      ansible.builtin.shell: kubectl get nodes
      register: result
    - name: stdout
      ansible.builtin.debug:
        msg: "{{ result.stdout.split('\n') }}"
    - name: Specifying a destination path
      become: yes
      ansible.builtin.fetch:
        src: /home/ubuntu/.kube/config
        dest: ~/.kube/config
        flat: yes