global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "security"
    static_configs:
    - targets: ["security:3000"]
    metrics_path: "/metrics"

  - job_name: "uploader"
    static_configs:
    - targets: ["uploader:3000"]
    metrics_path: "/metrics"

  - job_name: "storage"
    static_configs:
      - targets: [ "minio:9000" ]
    metrics_path: "/minio/v2/metrics/cluster"