node (label: 'centos8stream') {
    stage("Git checkout"){
        git credentialsId: 'c9e14b59-7949-4199-a9da-52f1c0d930cc', url: 'git@github.com:aragastmatb/example-playbook.git'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    stage('get repo vector-role with tag 1.1.0') {
        dir('./roles/java') {
            checkout([$class: 'GitSCM', branches: [[name: '1.0.1']], extensions: [], userRemoteConfigs: [[credentialsId: 'c9e14b59-7949-4199-a9da-52f1c0d930cc', url: 'git@github.com:netology-code/mnt-homeworks-ansible.git']]])
        }
    }

    stage("Run playbook"){
        if (secret_check){
            if (params.prod_run){
                sh 'ansible-playbook site.yml -i inventory/prod.yml -e "ansible_become_password=password" -vvv'
            }
            else{
                sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff --user=cloud-user --extra-vars "ansible_sudo_pass=password"'
            }
        }
        else{
            echo 'need more action'
        }
    }
}
    stage("Sample define secret_check"){
        sh 'docker run -dt --name centos centos'
    }