node (label: 'centos8stream') {
    stage("Git checkout"){
        git credentialsId: '2844bee6-94bf-4c3b-ad15-f48b41ddc99a', url: 'git@github.com:aragastmatb/example-playbook.git'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    stage("Download dependencies"){
        sh 'ansible-galaxy install -r requirements.yml -p roles'
    }
    stage("Run playbook"){
        if (secret_check){
            if (params.prod_run){
                sh 'ansible-playbook site.yml -i inventory/prod.yml'
            }
            else{
                sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff'
            }
        }
        else{
            echo 'need more action'
        }
    }
}