---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    qbec.io/component: app
  labels:
    app: demoapp
    qbec.io/application: demoapp
    qbec.io/environment: stage
  name: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: keqpup232/nginx:v1.0.0
        imagePullPolicy: Always
        name: demoapp
        ports:
        - containerPort: 8585

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    qbec.io/component: app
  labels:
    qbec.io/application: demoapp
    qbec.io/environment: stage
  name: demoapp
spec:
  ports:
  - name: web
    nodePort: 30555
    port: 8585
    targetPort: 80
  selector:
    app: demoapp
  type: NodePort