version: '3.3'
services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "pass"
    volumes:
      - my-db-postgre:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  my-db-postgre: