---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 178.154.198.19
    jenkins-agent-01:
      ansible_host: 178.154.195.137
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos