{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU exporter idle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU used"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\"}",
     "legendFormat": "load 1"
    },
    {
     "expr": "node_load5{job=\"node\"}",
     "legendFormat": "load 5"
    },
    {
     "expr": "node_load15{job=\"node\"}",
     "legendFormat": "load 15"
    }
   ]
  },
  {
   "title": "Free mem",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\"} /(1024*1024)"
    }
   ]
  },
  {
   "title": "Total-Free mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}/(1024*1024)",
     "legendFormat": "Free mem"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\"}/(1024*1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Free mem filesystem",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} / (1024 * 1024 *1024)"
    }
   ]
  },
  {
   "title": "Busy-Total filemem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} / (1024 * 1024 *1024))-(node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} / (1024 * 1024 *1024))",
     "legendFormat": "Busy"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} / (1024 * 1024 *1024)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}