kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.claimName }}-{{ .Release.Name }}
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}