apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: demo
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://51.250.93.74:6443
    stage:
      defaultNamespace: stage
      server: https://51.250.93.74:6443
    prod:
      defaultNamespace: prod
      server: https://51.250.93.74:6443
      includes:
        - endpoint
  vars: {}
  excludes:
    - endpoint